[tools]
actionlint = "1.7.12"
betterleaks = "latest"
buf = "1.71.0"
go = "1.26"
golangci-lint = "v2.12.2"
lefthook = "latest"
oras = "latest"
task = "latest"

[hooks]
postinstall = "if [ -z \"${CI:-}\" ] && git rev-parse --git-dir > /dev/null 2>&1; then lefthook install; fi"

[settings]
experimental = true
