# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
    proto:
        desc: Lint proto and regenerate connect-go code for development.
        cmds:
            - task: proto:lint
            - task: proto:gen:go

    proto:write-authz:
        desc: Write authz proto to proto directory.
        cmds:
          - go tool protoc-gen-authz-go --write-proto proto

    proto:lint:
        desc: Lint proto.
        deps:
          - proto:write-authz
        cmds:
            - buf lint

    proto:gen:go:
        desc: Regenerate connect-go code from proto.
        deps:
          - proto:write-authz
        cmds:
            - buf generate --template buf.gen.go.yaml
        sources:
            - "proto/**/*.proto"
            - buf.yaml
            - buf.gen.go.yaml
        generates:
            - "gen/**/*"

    proto:gen:es:
        desc: Regenerate connect-es code from proto.
        deps:
          - proto:write-authz
        cmds:
            - buf generate --template buf.gen.es.yaml
        sources:
            - "proto/**/*.proto"
            - buf.yaml
            - buf.gen.es.yaml
            - clients/connect-es/package.json
        generates:
            - "clients/connect-es/gen/**/*"
