// Code generated by MockGen. DO NOT EDIT.
// Source: ../../repository/tenant.go
//
// Generated by this command:
//
//	mockgen -source=../../repository/tenant.go -destination=mock_tenant_repository_test.go -package=connect
//

// Package connect is a generated GoMock package.
package connect

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/pj-hoakari/tolo-tenant-management/internal/domain"
	repository "github.com/pj-hoakari/tolo-tenant-management/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactor is a mock of Transactor interface.
type MockTransactor struct {
	ctrl     *gomock.Controller
	recorder *MockTransactorMockRecorder
	isgomock struct{}
}

// MockTransactorMockRecorder is the mock recorder for MockTransactor.
type MockTransactorMockRecorder struct {
	mock *MockTransactor
}

// NewMockTransactor creates a new mock instance.
func NewMockTransactor(ctrl *gomock.Controller) *MockTransactor {
	mock := &MockTransactor{ctrl: ctrl}
	mock.recorder = &MockTransactorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactor) EXPECT() *MockTransactorMockRecorder {
	return m.recorder
}

// WithinTransaction mocks base method.
func (m *MockTransactor) WithinTransaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithinTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithinTransaction indicates an expected call of WithinTransaction.
func (mr *MockTransactorMockRecorder) WithinTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithinTransaction", reflect.TypeOf((*MockTransactor)(nil).WithinTransaction), ctx, fn)
}

// MockTenantRepository is a mock of TenantRepository interface.
type MockTenantRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTenantRepositoryMockRecorder
	isgomock struct{}
}

// MockTenantRepositoryMockRecorder is the mock recorder for MockTenantRepository.
type MockTenantRepositoryMockRecorder struct {
	mock *MockTenantRepository
}

// NewMockTenantRepository creates a new mock instance.
func NewMockTenantRepository(ctrl *gomock.Controller) *MockTenantRepository {
	mock := &MockTenantRepository{ctrl: ctrl}
	mock.recorder = &MockTenantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantRepository) EXPECT() *MockTenantRepositoryMockRecorder {
	return m.recorder
}

// CreateEvent mocks base method.
func (m *MockTenantRepository) CreateEvent(arg0 context.Context, arg1 domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockTenantRepositoryMockRecorder) CreateEvent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockTenantRepository)(nil).CreateEvent), arg0, arg1)
}

// CreatePendingTenant mocks base method.
func (m *MockTenantRepository) CreatePendingTenant(arg0 context.Context, arg1 domain.Tenant, arg2 domain.OwnershipClaim) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePendingTenant", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePendingTenant indicates an expected call of CreatePendingTenant.
func (mr *MockTenantRepositoryMockRecorder) CreatePendingTenant(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePendingTenant", reflect.TypeOf((*MockTenantRepository)(nil).CreatePendingTenant), arg0, arg1, arg2)
}

// CreateTenant mocks base method.
func (m *MockTenantRepository) CreateTenant(arg0 context.Context, arg1 domain.Tenant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTenant", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTenant indicates an expected call of CreateTenant.
func (mr *MockTenantRepositoryMockRecorder) CreateTenant(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenant", reflect.TypeOf((*MockTenantRepository)(nil).CreateTenant), arg0, arg1)
}

// DeleteExpiredPendingTenants mocks base method.
func (m *MockTenantRepository) DeleteExpiredPendingTenants(arg0 context.Context, arg1 time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredPendingTenants", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpiredPendingTenants indicates an expected call of DeleteExpiredPendingTenants.
func (mr *MockTenantRepositoryMockRecorder) DeleteExpiredPendingTenants(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredPendingTenants", reflect.TypeOf((*MockTenantRepository)(nil).DeleteExpiredPendingTenants), arg0, arg1)
}

// FindEventByPublicID mocks base method.
func (m *MockTenantRepository) FindEventByPublicID(arg0 context.Context, arg1 string) (domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindEventByPublicID", arg0, arg1)
	ret0, _ := ret[0].(domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindEventByPublicID indicates an expected call of FindEventByPublicID.
func (mr *MockTenantRepositoryMockRecorder) FindEventByPublicID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindEventByPublicID", reflect.TypeOf((*MockTenantRepository)(nil).FindEventByPublicID), arg0, arg1)
}

// FindObservationSettingsByEventPublicID mocks base method.
func (m *MockTenantRepository) FindObservationSettingsByEventPublicID(arg0 context.Context, arg1 string) (domain.ObservationSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindObservationSettingsByEventPublicID", arg0, arg1)
	ret0, _ := ret[0].(domain.ObservationSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindObservationSettingsByEventPublicID indicates an expected call of FindObservationSettingsByEventPublicID.
func (mr *MockTenantRepositoryMockRecorder) FindObservationSettingsByEventPublicID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindObservationSettingsByEventPublicID", reflect.TypeOf((*MockTenantRepository)(nil).FindObservationSettingsByEventPublicID), arg0, arg1)
}

// FindTenantByID mocks base method.
func (m *MockTenantRepository) FindTenantByID(arg0 context.Context, arg1 string) (domain.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTenantByID", arg0, arg1)
	ret0, _ := ret[0].(domain.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTenantByID indicates an expected call of FindTenantByID.
func (mr *MockTenantRepositoryMockRecorder) FindTenantByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTenantByID", reflect.TypeOf((*MockTenantRepository)(nil).FindTenantByID), arg0, arg1)
}

// FindTenantByPublicID mocks base method.
func (m *MockTenantRepository) FindTenantByPublicID(arg0 context.Context, arg1 string) (domain.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTenantByPublicID", arg0, arg1)
	ret0, _ := ret[0].(domain.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTenantByPublicID indicates an expected call of FindTenantByPublicID.
func (mr *MockTenantRepositoryMockRecorder) FindTenantByPublicID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTenantByPublicID", reflect.TypeOf((*MockTenantRepository)(nil).FindTenantByPublicID), arg0, arg1)
}

// FindTenantByPublicIDForUpdate mocks base method.
func (m *MockTenantRepository) FindTenantByPublicIDForUpdate(arg0 context.Context, arg1 string) (domain.Tenant, domain.OwnershipClaim, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTenantByPublicIDForUpdate", arg0, arg1)
	ret0, _ := ret[0].(domain.Tenant)
	ret1, _ := ret[1].(domain.OwnershipClaim)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindTenantByPublicIDForUpdate indicates an expected call of FindTenantByPublicIDForUpdate.
func (mr *MockTenantRepositoryMockRecorder) FindTenantByPublicIDForUpdate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTenantByPublicIDForUpdate", reflect.TypeOf((*MockTenantRepository)(nil).FindTenantByPublicIDForUpdate), arg0, arg1)
}

// ListEventsByTenantID mocks base method.
func (m *MockTenantRepository) ListEventsByTenantID(ctx context.Context, tenantID string, filter repository.ListEventsFilter) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEventsByTenantID", ctx, tenantID, filter)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEventsByTenantID indicates an expected call of ListEventsByTenantID.
func (mr *MockTenantRepositoryMockRecorder) ListEventsByTenantID(ctx, tenantID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEventsByTenantID", reflect.TypeOf((*MockTenantRepository)(nil).ListEventsByTenantID), ctx, tenantID, filter)
}

// MarkTenantOwned mocks base method.
func (m *MockTenantRepository) MarkTenantOwned(arg0 context.Context, arg1 domain.Tenant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkTenantOwned", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkTenantOwned indicates an expected call of MarkTenantOwned.
func (mr *MockTenantRepositoryMockRecorder) MarkTenantOwned(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkTenantOwned", reflect.TypeOf((*MockTenantRepository)(nil).MarkTenantOwned), arg0, arg1)
}

// UpdateEvent mocks base method.
func (m *MockTenantRepository) UpdateEvent(arg0 context.Context, arg1 domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEvent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEvent indicates an expected call of UpdateEvent.
func (mr *MockTenantRepositoryMockRecorder) UpdateEvent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEvent", reflect.TypeOf((*MockTenantRepository)(nil).UpdateEvent), arg0, arg1)
}

// UpdateObservationSettings mocks base method.
func (m *MockTenantRepository) UpdateObservationSettings(arg0 context.Context, arg1 string, arg2 domain.ObservationSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateObservationSettings", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateObservationSettings indicates an expected call of UpdateObservationSettings.
func (mr *MockTenantRepositoryMockRecorder) UpdateObservationSettings(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateObservationSettings", reflect.TypeOf((*MockTenantRepository)(nil).UpdateObservationSettings), arg0, arg1, arg2)
}

// UpdateTenant mocks base method.
func (m *MockTenantRepository) UpdateTenant(arg0 context.Context, arg1 domain.Tenant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTenant", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTenant indicates an expected call of UpdateTenant.
func (mr *MockTenantRepositoryMockRecorder) UpdateTenant(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTenant", reflect.TypeOf((*MockTenantRepository)(nil).UpdateTenant), arg0, arg1)
}
