// Code generated by MockGen. DO NOT EDIT.
// Source: jwt_validator.go
//
// Generated by this command:
//
//	mockgen -source=jwt_validator.go -destination=mock_jwt_validator_test.go -package=connect
//

// Package connect is a generated GoMock package.
package connect

import (
	context "context"
	reflect "reflect"

	jwks "github.com/pj-hoakari/tolo-tenant-management/internal/jwks"
	gomock "go.uber.org/mock/gomock"
)

// MockJWTValidator is a mock of JWTValidator interface.
type MockJWTValidator struct {
	ctrl     *gomock.Controller
	recorder *MockJWTValidatorMockRecorder
	isgomock struct{}
}

// MockJWTValidatorMockRecorder is the mock recorder for MockJWTValidator.
type MockJWTValidatorMockRecorder struct {
	mock *MockJWTValidator
}

// NewMockJWTValidator creates a new mock instance.
func NewMockJWTValidator(ctrl *gomock.Controller) *MockJWTValidator {
	mock := &MockJWTValidator{ctrl: ctrl}
	mock.recorder = &MockJWTValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTValidator) EXPECT() *MockJWTValidatorMockRecorder {
	return m.recorder
}

// Claims mocks base method.
func (m *MockJWTValidator) Claims(arg0 context.Context, arg1 string) (jwks.InternalJWTClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Claims", arg0, arg1)
	ret0, _ := ret[0].(jwks.InternalJWTClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Claims indicates an expected call of Claims.
func (mr *MockJWTValidatorMockRecorder) Claims(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Claims", reflect.TypeOf((*MockJWTValidator)(nil).Claims), arg0, arg1)
}
