// Code generated by MockGen. DO NOT EDIT.
// Source: ../repository/membership.go
//
// Generated by this command:
//
//	mockgen -source=../repository/membership.go -destination=mock_membership_repository_test.go -package=application_test
//

// Package application_test is a generated GoMock package.
package application_test

import (
	context "context"
	reflect "reflect"

	domain "github.com/pj-hoakari/tolo-tenant-management/internal/relation/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockMembershipRepository is a mock of MembershipRepository interface.
type MockMembershipRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMembershipRepositoryMockRecorder
	isgomock struct{}
}

// MockMembershipRepositoryMockRecorder is the mock recorder for MockMembershipRepository.
type MockMembershipRepositoryMockRecorder struct {
	mock *MockMembershipRepository
}

// NewMockMembershipRepository creates a new mock instance.
func NewMockMembershipRepository(ctrl *gomock.Controller) *MockMembershipRepository {
	mock := &MockMembershipRepository{ctrl: ctrl}
	mock.recorder = &MockMembershipRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMembershipRepository) EXPECT() *MockMembershipRepositoryMockRecorder {
	return m.recorder
}

// AddTenantMember mocks base method.
func (m *MockMembershipRepository) AddTenantMember(ctx context.Context, tenantID, userID string, role domain.Role) (domain.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTenantMember", ctx, tenantID, userID, role)
	ret0, _ := ret[0].(domain.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTenantMember indicates an expected call of AddTenantMember.
func (mr *MockMembershipRepositoryMockRecorder) AddTenantMember(ctx, tenantID, userID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTenantMember", reflect.TypeOf((*MockMembershipRepository)(nil).AddTenantMember), ctx, tenantID, userID, role)
}

// ChangeTenantRole mocks base method.
func (m *MockMembershipRepository) ChangeTenantRole(ctx context.Context, tenantID, userID string, role domain.Role) (domain.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeTenantRole", ctx, tenantID, userID, role)
	ret0, _ := ret[0].(domain.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeTenantRole indicates an expected call of ChangeTenantRole.
func (mr *MockMembershipRepositoryMockRecorder) ChangeTenantRole(ctx, tenantID, userID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeTenantRole", reflect.TypeOf((*MockMembershipRepository)(nil).ChangeTenantRole), ctx, tenantID, userID, role)
}

// FindMembership mocks base method.
func (m *MockMembershipRepository) FindMembership(ctx context.Context, tenantID, userID string) (domain.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMembership", ctx, tenantID, userID)
	ret0, _ := ret[0].(domain.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMembership indicates an expected call of FindMembership.
func (mr *MockMembershipRepositoryMockRecorder) FindMembership(ctx, tenantID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMembership", reflect.TypeOf((*MockMembershipRepository)(nil).FindMembership), ctx, tenantID, userID)
}

// FindTenantRoleForShare mocks base method.
func (m *MockMembershipRepository) FindTenantRoleForShare(ctx context.Context, tenantID, userID string) (domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTenantRoleForShare", ctx, tenantID, userID)
	ret0, _ := ret[0].(domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTenantRoleForShare indicates an expected call of FindTenantRoleForShare.
func (mr *MockMembershipRepositoryMockRecorder) FindTenantRoleForShare(ctx, tenantID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTenantRoleForShare", reflect.TypeOf((*MockMembershipRepository)(nil).FindTenantRoleForShare), ctx, tenantID, userID)
}

// GrantEventRole mocks base method.
func (m *MockMembershipRepository) GrantEventRole(ctx context.Context, eventID, userID string, role domain.Role) (domain.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantEventRole", ctx, eventID, userID, role)
	ret0, _ := ret[0].(domain.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GrantEventRole indicates an expected call of GrantEventRole.
func (mr *MockMembershipRepositoryMockRecorder) GrantEventRole(ctx, eventID, userID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantEventRole", reflect.TypeOf((*MockMembershipRepository)(nil).GrantEventRole), ctx, eventID, userID, role)
}

// ListMembershipsByTenant mocks base method.
func (m *MockMembershipRepository) ListMembershipsByTenant(ctx context.Context, tenantID string) ([]domain.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembershipsByTenant", ctx, tenantID)
	ret0, _ := ret[0].([]domain.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembershipsByTenant indicates an expected call of ListMembershipsByTenant.
func (mr *MockMembershipRepositoryMockRecorder) ListMembershipsByTenant(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembershipsByTenant", reflect.TypeOf((*MockMembershipRepository)(nil).ListMembershipsByTenant), ctx, tenantID)
}

// LockTenantMemberships mocks base method.
func (m *MockMembershipRepository) LockTenantMemberships(ctx context.Context, tenantID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockTenantMemberships", ctx, tenantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockTenantMemberships indicates an expected call of LockTenantMemberships.
func (mr *MockMembershipRepositoryMockRecorder) LockTenantMemberships(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockTenantMemberships", reflect.TypeOf((*MockMembershipRepository)(nil).LockTenantMemberships), ctx, tenantID)
}

// RevokeEventRole mocks base method.
func (m *MockMembershipRepository) RevokeEventRole(ctx context.Context, eventID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeEventRole", ctx, eventID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeEventRole indicates an expected call of RevokeEventRole.
func (mr *MockMembershipRepositoryMockRecorder) RevokeEventRole(ctx, eventID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeEventRole", reflect.TypeOf((*MockMembershipRepository)(nil).RevokeEventRole), ctx, eventID, userID)
}

// RevokeTenantMembership mocks base method.
func (m *MockMembershipRepository) RevokeTenantMembership(ctx context.Context, tenantID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeTenantMembership", ctx, tenantID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeTenantMembership indicates an expected call of RevokeTenantMembership.
func (mr *MockMembershipRepositoryMockRecorder) RevokeTenantMembership(ctx, tenantID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeTenantMembership", reflect.TypeOf((*MockMembershipRepository)(nil).RevokeTenantMembership), ctx, tenantID, userID)
}
