// Code generated by MockGen. DO NOT EDIT.
// Source: ../repository/tenant.go
//
// Generated by this command:
//
//	mockgen -source=../repository/tenant.go -destination=mock_tenant_repository_test.go -package=application_test
//

// Package application_test is a generated GoMock package.
package application_test

import (
	context "context"
	reflect "reflect"

	domain "github.com/pj-hoakari/tolo-tenant-management/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTenantRepository is a mock of TenantRepository interface.
type MockTenantRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTenantRepositoryMockRecorder
	isgomock struct{}
}

// MockTenantRepositoryMockRecorder is the mock recorder for MockTenantRepository.
type MockTenantRepositoryMockRecorder struct {
	mock *MockTenantRepository
}

// NewMockTenantRepository creates a new mock instance.
func NewMockTenantRepository(ctrl *gomock.Controller) *MockTenantRepository {
	mock := &MockTenantRepository{ctrl: ctrl}
	mock.recorder = &MockTenantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantRepository) EXPECT() *MockTenantRepositoryMockRecorder {
	return m.recorder
}

// CreateEvent mocks base method.
func (m *MockTenantRepository) CreateEvent(arg0 context.Context, arg1 domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockTenantRepositoryMockRecorder) CreateEvent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockTenantRepository)(nil).CreateEvent), arg0, arg1)
}

// CreateTenant mocks base method.
func (m *MockTenantRepository) CreateTenant(arg0 context.Context, arg1 domain.Tenant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTenant", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTenant indicates an expected call of CreateTenant.
func (mr *MockTenantRepositoryMockRecorder) CreateTenant(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenant", reflect.TypeOf((*MockTenantRepository)(nil).CreateTenant), arg0, arg1)
}

// DeleteTenant mocks base method.
func (m *MockTenantRepository) DeleteTenant(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTenant", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTenant indicates an expected call of DeleteTenant.
func (mr *MockTenantRepositoryMockRecorder) DeleteTenant(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTenant", reflect.TypeOf((*MockTenantRepository)(nil).DeleteTenant), arg0, arg1)
}

// FindEventByID mocks base method.
func (m *MockTenantRepository) FindEventByID(arg0 context.Context, arg1 string) (domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindEventByID", arg0, arg1)
	ret0, _ := ret[0].(domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindEventByID indicates an expected call of FindEventByID.
func (mr *MockTenantRepositoryMockRecorder) FindEventByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindEventByID", reflect.TypeOf((*MockTenantRepository)(nil).FindEventByID), arg0, arg1)
}

// FindTenantByPublicID mocks base method.
func (m *MockTenantRepository) FindTenantByPublicID(arg0 context.Context, arg1 string) (domain.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTenantByPublicID", arg0, arg1)
	ret0, _ := ret[0].(domain.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTenantByPublicID indicates an expected call of FindTenantByPublicID.
func (mr *MockTenantRepositoryMockRecorder) FindTenantByPublicID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTenantByPublicID", reflect.TypeOf((*MockTenantRepository)(nil).FindTenantByPublicID), arg0, arg1)
}

// UpdateEvent mocks base method.
func (m *MockTenantRepository) UpdateEvent(arg0 context.Context, arg1 domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEvent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEvent indicates an expected call of UpdateEvent.
func (mr *MockTenantRepositoryMockRecorder) UpdateEvent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEvent", reflect.TypeOf((*MockTenantRepository)(nil).UpdateEvent), arg0, arg1)
}
