// Code generated by "stringer -type=Role -trimprefix=Role -linecomment -output=role_enum_string.go"; DO NOT EDIT.

package domain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RoleUnspecified-0]
	_ = x[RoleOwner-1]
	_ = x[RoleStaff-2]
	_ = x[RoleAdmin-3]
}

const _Role_name = "unspecifiedownerstaffadmin"

var _Role_index = [...]uint8{0, 11, 16, 21, 26}

func (i Role) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Role_index)-1 {
		return "Role(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Role_name[_Role_index[idx]:_Role_index[idx+1]]
}
