// Code generated by "stringer -type=EventType,EventStatus -trimprefix=Event -linecomment -output=event_enum_string.go"; DO NOT EDIT.

package domain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventTypeUnspecified-0]
	_ = x[EventTypeShortTerm-1]
	_ = x[EventTypeLongTerm-2]
}

const _EventType_name = "unspecifiedshort_termlong_term"

var _EventType_index = [...]uint8{0, 11, 21, 30}

func (i EventType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_EventType_index)-1 {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[idx]:_EventType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventStatusUnspecified-0]
	_ = x[EventStatusDraft-1]
	_ = x[EventStatusOpen-2]
	_ = x[EventStatusLocked-3]
	_ = x[EventStatusClosed-4]
	_ = x[EventStatusArchived-5]
}

const _EventStatus_name = "unspecifieddraftopenlockedclosedarchived"

var _EventStatus_index = [...]uint8{0, 11, 16, 20, 26, 32, 40}

func (i EventStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_EventStatus_index)-1 {
		return "EventStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventStatus_name[_EventStatus_index[idx]:_EventStatus_index[idx+1]]
}
