// Code generated by "stringer -type=TenantOwnershipState -trimprefix=TenantOwnershipState -linecomment -output=tenant_enum_string.go"; DO NOT EDIT.

package domain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TenantOwnershipStateUnspecified-0]
	_ = x[TenantOwnershipStatePendingOwner-1]
	_ = x[TenantOwnershipStateOwned-2]
}

const _TenantOwnershipState_name = "unspecifiedpending_ownerowned"

var _TenantOwnershipState_index = [...]uint8{0, 11, 24, 29}

func (i TenantOwnershipState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TenantOwnershipState_index)-1 {
		return "TenantOwnershipState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TenantOwnershipState_name[_TenantOwnershipState_index[idx]:_TenantOwnershipState_index[idx+1]]
}
